### PR TITLE
UIEH-121: add title search results sorting

### PR DESCRIPTION
**Pull request by MaksymDryha**
## Purpose
Users should have the ability to choose in which manner to sort title search results (by relevance or alphabetically)

## Approach
* Adjust TitleSearchFilters component so that sorting filter appears among other filters 
* Write related tests

### Before:
image

### CODE REVIEW

**Comment by MaksymDryha** [comment]
@sduvvuri-ebsco, I decided not to use those methods, because it wouldn't do a lot of profit. Nothing changes on the frontend side, depending on how returned items are sorted.

**Comment by MaksymDryha** [comment]
@sduvvuri-ebsco, I decided not to use those methods, because it wouldn't do a lot of profit. Nothing changes on the frontend side, depending on how returned items are sorted.

**Comment by MaksymDryha** [comment]
@sduvvuri-ebsco, I decided not to use those methods, because it wouldn't do a lot of profit. Nothing changes on the frontend side, depending on how returned items are sorted.

**Comment by MaksymDryha** [comment]
@sduvvuri-ebsco, I decided not to use those methods, because it wouldn't do a lot of profit. Nothing changes on the frontend side, depending on how returned items are sorted.

**Comment by MaksymDryha** [comment]
@sduvvuri-ebsco, I decided not to use those methods, because it wouldn't do a lot of profit. Nothing changes on the frontend side, depending on how returned items are sorted.

**Comment by MaksymDryha** [comment]
@sduvvuri-ebsco, I decided not to use those methods, because it wouldn't do a lot of profit. Nothing changes on the frontend side, depending on how returned items are sorted.

**Comment by MaksymDryha** [comment]
@sduvvuri-ebsco, I decided not to use those methods, because it wouldn't do a lot of profit. Nothing changes on the frontend side, depending on how returned items are sorted.

**Comment by carolegodfrey** [comment]
Just an added note on the sort helper method for the tests -- they get applied under the hood. You should not need to explicitly call them. In this case the sort results will only be different if there is a multiple term search performed. For example searching for 'heart attack' will return results containing both heart and attack as more relevant.

**Pull request merged**
