### PR TITLE
Refactor to MirageJS

### PR DESCRIPTION
**Pull request by minkimcello**
## Motivation
Screen Shot 2020-07-14 at 4 57 15 PM
This is part of an on-going initiative to completely migrate all of `folio-org` projects from `@bigtest/mirage` to `miragejs`.

[`@bigtest/mirage`](https://github.com/bigtestjs/mirage/) was originally a prototype to make `mirage` available to any framework, but it has since been archived in favor of [`miragejs`](https://miragejs.com/). The documentation for `miragejs` is not only prodigious for its extensive API docs but also for its tutorials and guides. Furthermore, it receives regular bug-fixes and maintenance releases in thanks to its extremely large and active community.

Previous PR: [@folio-org/ui-requests #618](https://github.com/folio-org/ui-requests/pull/618)
_Linking the previous pull request so that subsequent ones can be found tagged below._

<details>
<summary>Overview of progress at the time of the creation of this PR (in chronological order):</summary>
<br>
✅ <code>ui-checkin</code>
<br>
✅ <code>ui-checkout</code>
<br>
☑️ <code>ui-circulation</code>
<br>
☑️ <code>ui-calendar</code>
<br>
✅ <code>ui-agreements</code>
<br>
☑️ <code>ui-app-template</code>
<br>
☑️ <code>ui-inventory</code>
<br>
☑️ <code>ui-data-export</code>
<br>
✅ <code>ui-finc-config</code>
<br>
☑️ <code>ui-licenses</code>
<br>
☑️ <code>ui-erm-comparisons</code>
<br>
☑️ <code>ui-myprofile</code>
<br>
☑️ <code>ui-local-kb-admin</code>
<br>
☑️ <code>ui-marccat</code>
<br>
☑️ <code>ui-finc-select</code>
<br>
☑️ <code>ui-erm-usage</code>
<br>
☑️ <code>ui-notes</code>
<br>
☑️ <code>ui-oai-pmh</code>
<br>
☑️ <code>ui-plugin-find-user</code>
<br>
☑️ <code>ui-plugin-find-eresource</code>
<br>
☑️ <code>ui-plugin-find-package-title</code>
<br>
☑️ <code>ui-plugin-find-import-profile</code>
<br>
☑️ <code>ui-search</code>
<br>
☑️ <code>ui-tenant-settings</code>
<br>
☑️ <code>ui-requests</code>
<br>
☑️ <code>ui-eholdings</code>
</details>

## Approach
- [x] Cloned, installed, and then ran tests to double check that the tests are passing before refactoring.
- [x] Removed `@bigtest/mirage` and added `inflected`, `faker`, and `miragejs`.
- [x] ESlint & ran tests after the refactor to confirm they all pass.
- [x] Updated CHANGELOG.
- [ ] CircleCI write access problem

### CODE REVIEW

**Comment by minkimcello** [comment]
@zburke @BogdanDenis Can you help me sort out the circle CI access issue?
```
Warning: Permanently added the RSA host key for IP address '***.**.****' to the list of known hosts.

Permission denied (publickey).
```

**Comment by zburke** [comment]
@minkimcello, TBH, CircleCI was a Frontside thing that was never adopted by Folio as an organization since we already have established expertise and resources devoted to Jenkins. There isn't enough detail in that error message for me to figure out what's going on. 

The only hunch I have is that maybe this is due to which CircleCI project "owns" this GitHub project. It appears there is both a `frontside-folio` organization and a `folio-org` organization. Maybe there's a clue there? If not, I can follow up with our dev-ops folks but I'm not really sure what I'll be asking. 

Sorry I don't have more insight here.

**Comment by minkimcello** [comment]
@zburke If it's not integrated to folio's development workflow, can I disable it for the time being? 

@BogdanDenis @MaksymDryha @Vladyslav-Velytskyi

**Comment by zburke** [comment]
> @zburke If it's not integrated to folio's development workflow, can I disable it for the time being?

Let's let @BogdanDenis make that call.

**Comment by BogdanDenis** [comment]
Hi @minkimcello, CircleCI is not longer in use and we really ought to just disable it, we just don't have permissions to do this. I'm going to raise this with the team again.

**Pull request merged**
