### PR TITLE
Run tests on Jenkins and scan with SonarQube

### PR DESCRIPTION
**Pull request by cherewaty**

### CODE REVIEW

**Comment by sduvvuri-ebsco** [comment]
Doesn't this mean that tests and lint will be run both by Circle and Jenkins? Are we going to disable Circle?

**Comment by cherewaty** [comment]
The next step after this is to disable Circle, yes.

**Comment by sduvvuri-ebsco** [comment]
Will Jenkins support running tests on both Chrome and Firefox like we do today in Circle?

**Comment by funkymalc** [comment]
@sduvvuri-ebsco - I have a stub for FF but it isn't enabled.  I'll work on getting that enabled.

**Comment by funkymalc** [comment]
@cherewaty - disable sonarqube in this PR.  I'll add it directly to master after you merge since the scan needs to run on master once before other branches can be scanned.

**Comment by cherewaty** [comment]
SonarQube line removed.

**Comment by cherewaty** [comment]
@funkymalc could you hop into Circle (you should be able to log in with your GitHub credentials) and turn the builds there off? It should be fairly easy to find, but let me know if you can't find the switch.

**Comment by cherewaty** [comment]
https://circleci.com/gh/folio-org/ui-eholdings

**Pull request merged**
